# Development

name = "miniflare-esbuild-ava"
type = "javascript"
account_id = ""
workers_dev = true
route = ""
zone_id = ""

# Compatibility flags https://github.com/cloudflare/wrangler/pull/2009
compatibility_date = "2021-08-23"
compatibility_flags = [ "formdata_parser_supports_files" ]

[vars]
ENV = "dev"
DEBUG = "true"

[build]
command = "npm run build"
watch_dir = "src"

[build.upload]
format = "service-worker"
